modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"
[[mods]] #mandatory
modId="incompetent_druidry" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="${mod_authors}" #optional
description='''${mod_description}'''
[[mixins]]
config="incompetent_druidry.mixins.json"
[[dependencies.incompetent_druidry]] #optional
modId="neoforge" #mandatory
mandatory=true #mandatory
versionRange="${neo_version_range}" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.incompetent_druidry]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"